on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Create .env file with secrets
        shell: bash
        env:
          INFURA_API_KEY: "${{ secrets.INFURA_API_KEY }}"
          ALCHEMY_API_KEY: "${{ secrets.ALCHEMY_API_KEY }}"
          ROPSTEN_PRIVATE_KEY: "${{ secrets.ROPSTEN_PRIVATE_KEY }}"
        run: |
          touch .env
          echo INFURA_API_KEY="$INFURA_API_KEY" >> .env
          echo ALCHEMY_API_KEY="$ALCHEMY_API_KEY" >> .env
          echo ROPSTEN_PRIVATE_KEY="$ROPSTEN_PRIVATE_KEY" >> .env
      - run: yarn install
      - run: yarn compile
      - name: Fork Ethereum mainnet for testing
        env:
          ALCHEMY_API_KEY: "${{ secrets.ALCHEMY_API_KEY }}"
        run: nohup yarn hardhat node --fork https://eth-mainnet.alchemyapi.io/v2/"$ALCHEMY_API_KEY" &
      - run: yarn test
      - name: Remove .env and nohup.out file
        shell: bash
        run: |
          # nohup.out generated from fork script
          rm .env
          rm -f -- nohup.out
      - run: yarn lint
      - run: yarn prettier
